<?php
namespace CGM\Core\Providers\CGMAuthors;
use CGM\Core\Contracts\ProviderInterface;use CGM\Core\Plugin;use CGM\Core\Relationships\CallbackRelationshipStore;use CGM\Core\Objects\Adapters\CallbackObjectAdapter;
use CGM\Core\Objects\ObjectReference;use CGM\Core\Query\Providers\CallbackQueryProvider;
final class CGMAuthorsProvider implements ProviderInterface {
    public function id():string{return 'cgm-authors';}
    public function register(Plugin $core):void{if(!class_exists('CGM_Authors')&&!defined('CGM_AUTHORS_VERSION'))return;$version=defined('CGM_AUTHORS_VERSION')?CGM_AUTHORS_VERSION:'';$bridge=apply_filters('cgm_authors/core_bridge',array(),$core);$connected=is_array($bridge)&&is_callable($bridge['get']??null)&&is_callable($bridge['get_reverse']??null)&&is_callable($bridge['replace']??null);$store=$connected?new CallbackRelationshipStore($bridge):new CGMAuthorsRelationshipStore();$post_types=$connected?(array)($bridge['post_types']??$this->post_types()):$this->post_types();$post_types=array_values(array_filter(array_map('sanitize_key',$post_types),fn($pt)=>$core->content_types()->has($pt)));
        $core->providers()->register(array('id'=>$this->id(),'label'=>'CGM Authors','version'=>$version,'apis'=>array('core'=>'^2.0','relationships'=>'^2.0','query'=>'^2.0','dynamic_data'=>'^2.0'),'capabilities'=>array('relationships.authors','relationships.coauthors','dynamic_data.authors','editor.authors','query.authors'),'requires'=>array('wordpress'=>'*'),'status'=>$connected?'connected':'legacy-adapter','notes'=>$connected?'Connected through the CGM Authors Core bridge.':'Using a compatibility adapter for _cgm_authors. Guest credits are preserved during writes; a formal bridge unlocks guest objects and future storage changes.'));
        $core->relationships()->register_store('cgm-authors',$store);
        $common=array('source_type'=>'*','source_types'=>$post_types,'target_type'=>'user','target_types'=>array('user'),'store'=>'cgm-authors','provider'=>'cgm-authors','public'=>true,'multiple'=>true,'ordered'=>true,'assign_capability'=>'edit_posts','read_capability'=>'read');
        $core->relationships()->register_type(array_merge($common,array('id'=>'authors','label'=>__('Authors','cgm-core'),'reverse_label'=>__('Articles','cgm-core'),'primary'=>true,'primary_max'=>1,'roles'=>array('primary','author','contributor'))));
        $core->relationships()->register_type(array_merge($common,array('id'=>'co_authors','label'=>__('Co-authors','cgm-core'),'reverse_label'=>__('Co-authored content','cgm-core'),'primary'=>false,'roles'=>array('author','contributor'))));
        $core->editor_controls()->register(array('id'=>'co_authors','label'=>__('Co-authors','cgm-core'),'post_types'=>$post_types,'multiple'=>true,'kind'=>'relationship','relationship'=>'co_authors','schema'=>$core->relationships()->get_type('co_authors'),'get'=>static function(int $post_id)use($store){$out=array();foreach($store->get('co_authors',(string)get_post_type($post_id),$post_id) as $r){$u=get_userdata(absint($r['target_id']??0));if($u)$out[]=array('id'=>$u->ID,'label'=>$u->display_name,'role'=>$r['role']??'author','order'=>$r['order']??$r['sort_order']??0);}return $out;},'search'=>is_callable($bridge['search']??null)?$bridge['search']:static function(string $q){$users=get_users(array('search'=>$q?'*'.$q.'*':'','search_columns'=>array('display_name','user_login','user_email'),'number'=>30,'orderby'=>'display_name'));return array_map(static fn($u)=>array('id'=>$u->ID,'label'=>$u->display_name,'description'=>current_user_can('list_users')?$u->user_email:''),$users);},'set'=>static fn(int $post_id,array $items)=>$store->replace('co_authors',(string)get_post_type($post_id),$post_id,'user',$items)));
        $core->dynamic_data()->register(array('id'=>'authors.coauthors.names','label'=>__('Co-author names','cgm-core'),'type'=>'string','group'=>'CGM Authors','provider'=>'cgm-authors','resolve'=>static function($o)use($store){$id=$o instanceof ObjectReference?$o->id:($o instanceof \WP_Post?$o->ID:absint($o?:get_the_ID()));$names=array();foreach($store->get('co_authors',(string)get_post_type($id),$id) as $r){$u=get_userdata($r['target_id']);if($u)$names[]=$u->display_name;}return implode(', ',$names);}));
        $core->dynamic_data()->register(array('id'=>'authors.coauthors.ids','label'=>__('Co-author IDs','cgm-core'),'type'=>'array','group'=>'CGM Authors','provider'=>'cgm-authors','resolve'=>static function($o)use($store){$id=$o instanceof ObjectReference?$o->id:($o instanceof \WP_Post?$o->ID:absint($o?:get_the_ID()));return array_map(static fn($r)=>absint($r['target_id']),$store->get('co_authors',(string)get_post_type($id),$id));}));
        $this->register_guests($core,$bridge);
    }
    private function register_guests(Plugin $core,array $bridge):void{if(!is_callable($bridge['get_guests']??null))return;$core->dynamic_data()->register(array('id'=>'authors.guests','label'=>__('Guest authors','cgm-core'),'type'=>'array','group'=>'CGM Authors','provider'=>'cgm-authors','resolve'=>static fn($o)=>call_user_func($bridge['get_guests'],$o instanceof ObjectReference?$o->id:($o instanceof \WP_Post?$o->ID:absint($o?:get_the_ID())))));if(!is_callable($bridge['guest_exists']??null)||!is_callable($bridge['guest_label']??null))return;$core->content_types()->register(array('id'=>'guest_author','label'=>__('Guest author','cgm-core'),'plural_label'=>__('Guest authors','cgm-core'),'kind'=>'guest_author','subtype'=>'guest_author','provider'=>'cgm-authors','query_provider'=>is_callable($bridge['guest_query']??null)?'cgm-authors-guests':'','public'=>true,'rest'=>false));$core->objects()->register_adapter(new CallbackObjectAdapter('guest_author',array('exists'=>$bridge['guest_exists'],'label'=>$bridge['guest_label'],'url'=>$bridge['guest_url']??null,'edit_url'=>$bridge['guest_edit_url']??null,'is_public'=>$bridge['guest_public']??static fn()=>true,'property'=>$bridge['guest_property']??null,'search'=>$bridge['guest_search']??null)));if(is_callable($bridge['guest_query']??null))$core->query_providers()->register(new CallbackQueryProvider('cgm-authors-guests',array('run'=>$bridge['guest_query'],'explain'=>$bridge['guest_query_explain']??null),array('guest_author')));}
    private function post_types():array{$settings=get_option('cgm_authors_settings',array());$types=is_array($settings)?($settings['post_types']??array()):array();return $types?array_values(array_filter(array_map('sanitize_key',(array)$types))):array('post','review');}
}
