<?php
namespace CGM\Core\Relationships;
use CGM\Core\Contracts\QueryableRelationshipStoreInterface;
/** Network-wide relationship storage for explicit cross-site schemas. */
final class NetworkRelationshipStore implements QueryableRelationshipStoreInterface {
    // Deliberately does not extend CoreRelationshipStore: every method needs
    // blog columns, so nothing of the parent would be reusable.
    private function ntable():string{global $wpdb;return $wpdb->base_prefix.'cgm_core_network_relationships';}
    public static function install():void{if(!is_multisite())return;global $wpdb;$table=$wpdb->base_prefix.'cgm_core_network_relationships';$charset=$wpdb->get_charset_collate();require_once ABSPATH.'wp-admin/includes/upgrade.php';dbDelta("CREATE TABLE {$table} (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,relationship_key VARCHAR(100) NOT NULL,source_blog_id BIGINT UNSIGNED NOT NULL,source_type VARCHAR(100) NOT NULL,source_id BIGINT UNSIGNED NOT NULL,target_blog_id BIGINT UNSIGNED NOT NULL,target_type VARCHAR(100) NOT NULL,target_id BIGINT UNSIGNED NOT NULL,role VARCHAR(100) NOT NULL DEFAULT '',sort_order INT NOT NULL DEFAULT 0,is_primary TINYINT(1) NOT NULL DEFAULT 0,meta LONGTEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uniq_rel (relationship_key,source_blog_id,source_type,source_id,target_blog_id,target_type,target_id,role),KEY source_lookup (relationship_key,source_blog_id,source_type,source_id),KEY target_lookup (relationship_key,target_blog_id,target_type,target_id)) {$charset};");}
    public function get(string $r,string $st,int $sid,array $args=array()):array{global $wpdb;$blog=absint($args['source_blog_id']??get_current_blog_id());$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->ntable()} WHERE relationship_key=%s AND source_blog_id=%d AND source_type=%s AND source_id=%d ORDER BY is_primary DESC,sort_order ASC,id ASC",$r,$blog,$st,$sid),ARRAY_A)?:array();return array_map(array($this,'nhydrate'),$rows);}
    public function get_reverse(string $r,string $tt,int $tid,array $args=array()):array{global $wpdb;$blog=absint($args['target_blog_id']??get_current_blog_id());$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->ntable()} WHERE relationship_key=%s AND target_blog_id=%d AND target_type=%s AND target_id=%d ORDER BY is_primary DESC,sort_order ASC,id ASC",$r,$blog,$tt,$tid),ARRAY_A)?:array();return array_map(array($this,'nhydrate'),$rows);}
    public function replace(string $r,string $st,int $sid,string $tt,array $items):bool{global $wpdb;$table=$this->ntable();$source_blog=get_current_blog_id();$wpdb->query('START TRANSACTION');try{$x=$wpdb->delete($table,array('relationship_key'=>$r,'source_blog_id'=>$source_blog,'source_type'=>$st,'source_id'=>$sid),array('%s','%d','%s','%d'));if(false===$x)throw new \RuntimeException();$now=current_time('mysql',true);foreach(array_values($items) as $i=>$item){$id=absint($item['id']??$item['target_id']??0);if(!$id)continue;$target_blog=absint($item['target_blog_id']??$item['site_id']??$source_blog);$meta=(array)($item['meta']??array());$ok=$wpdb->insert($table,array('relationship_key'=>$r,'source_blog_id'=>$source_blog,'source_type'=>$st,'source_id'=>$sid,'target_blog_id'=>$target_blog,'target_type'=>$tt,'target_id'=>$id,'role'=>sanitize_key((string)($item['role']??'')),'sort_order'=>intval($item['order']??$i),'is_primary'=>!empty($item['primary'])?1:0,'meta'=>$meta?wp_json_encode($meta):null,'created_at'=>$now,'updated_at'=>$now));if(false===$ok)throw new \RuntimeException();}$wpdb->query('COMMIT');return true;}catch(\Throwable $e){$wpdb->query('ROLLBACK');return false;}}

    public function count_for_object(string $relationship,string $content_type,int $object_id):int{global $wpdb;$blog=get_current_blog_id();return (int)$wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM {$this->ntable()} WHERE relationship_key=%s AND ((source_blog_id=%d AND source_type=%s AND source_id=%d) OR (target_blog_id=%d AND target_type=%s AND target_id=%d))",$relationship,$blog,$content_type,$object_id,$blog,$content_type,$object_id));}
    public function delete_for_object(string $relationship,string $content_type,int $object_id):int|false{global $wpdb;$blog=get_current_blog_id();$result=$wpdb->query($wpdb->prepare("DELETE FROM {$this->ntable()} WHERE relationship_key=%s AND ((source_blog_id=%d AND source_type=%s AND source_id=%d) OR (target_blog_id=%d AND target_type=%s AND target_id=%d))",$relationship,$blog,$content_type,$object_id,$blog,$content_type,$object_id));return false===$result?false:(int)$result;}
    public function matching_source_ids(string $r,string $st,string $tt,string $op,mixed $v):array{global $wpdb;$blog=get_current_blog_id();$ids=array_values(array_filter(array_map('absint',is_array($v)?$v:explode(',',(string)$v))));if('EXISTS'===strtoupper($op))return array_map('absint',(array)$wpdb->get_col($wpdb->prepare("SELECT DISTINCT source_id FROM {$this->ntable()} WHERE relationship_key=%s AND source_blog_id=%d AND source_type=%s",$r,$blog,$st)));if(!$ids)return array();$ph=implode(',',array_fill(0,count($ids),'%d'));return array_map('absint',(array)$wpdb->get_col($wpdb->prepare("SELECT DISTINCT source_id FROM {$this->ntable()} WHERE relationship_key=%s AND source_blog_id=%d AND source_type=%s AND target_type=%s AND target_id IN ({$ph})",...array_merge(array($r,$blog,$st,$tt),$ids))));}
    public function sql_condition(string $r,string $st,string $tt,string $op,mixed $v,string $src):?array{return $this->sql_property_condition($r,$st,$tt,'target_id',$op,$v,$src);}
    public function sql_property_condition(string $r,string $st,string $tt,string $prop,string $op,mixed $v,string $src):?array{global $wpdb;$blog=get_current_blog_id();$op=strtoupper($op);$base="SELECT 1 FROM {$this->ntable()} nr WHERE nr.relationship_key=%s AND nr.source_blog_id=%d AND nr.source_type=%s AND nr.source_id={$src}";$params=array($r,$blog,$st);if(in_array($op,array('EXISTS','NOT EXISTS'),true))return array('sql'=>('NOT EXISTS'===$op?'NOT ':'')."EXISTS ({$base})",'params'=>$params);$key=sanitize_key(str_replace(array('meta.','meta:'),'',$prop));$expr=match($prop){'role'=>'nr.role','primary','is_primary'=>'nr.is_primary','order','sort_order'=>'nr.sort_order','target','target_id'=>'nr.target_id','target_blog_id','site_id'=>'nr.target_blog_id',default=>''===$key?'NULL':"JSON_UNQUOTE(JSON_EXTRACT(nr.meta, '$.\"{$key}\"'))"};if(in_array($op,array('IN','NOT IN'),true)){$vals=is_array($v)?array_values($v):array_map('trim',explode(',',(string)$v));$vals=array_values(array_filter(array_map(static fn($x)=>is_scalar($x)?(string)$x:'',$vals),static fn($x)=>''!==$x));if(!$vals)return array('sql'=>'NOT IN'===$op?'1=1':'1=0','params'=>array());$ph=implode(',',array_fill(0,count($vals),'%s'));$cond="{$expr} {$op} ({$ph})";}else{$vals=array(is_scalar($v)?(string)$v:'');$cond="{$expr} ".(in_array($op,array('=','!=','>','>=','<','<=','LIKE','NOT LIKE'),true)?$op:'=').' %s';}return array('sql'=>"EXISTS ({$base} AND {$cond})",'params'=>array_merge($params,$vals));}
    public function sql_wrap_condition(string $r,string $st,string $tt,string $selector,string $child,array $params,string $src):?array{global $wpdb;$base="SELECT 1 FROM {$this->ntable()} nr WHERE nr.relationship_key=%s AND nr.source_blog_id=%d AND nr.source_type=%s AND nr.source_id={$src} AND nr.target_type=%s";$baseparams=array($r,get_current_blog_id(),$st,$tt);if('primary'===$selector)$base.=' AND nr.is_primary=1';$child=str_replace('{{TARGET_ID}}','nr.target_id',$child);return array('sql'=>"EXISTS ({$base} AND ({$child}))",'params'=>array_merge($baseparams,$params));}
    public function sql_sort_expression(string $r,string $st,string $tt,string $property,string $selector,string $src):?array{$key=sanitize_key(str_replace(array('meta.','meta:'),'',$property));$expr=match($property){'role'=>'nr.role','primary','is_primary'=>'nr.is_primary','order','sort_order'=>'nr.sort_order','target','target_id'=>'nr.target_id','target_blog_id','site_id'=>'nr.target_blog_id',default=>''===$key?'NULL':"JSON_UNQUOTE(JSON_EXTRACT(nr.meta, '$.\"{$key}\"'))"};$where="nr.relationship_key=%s AND nr.source_blog_id=%d AND nr.source_type=%s AND nr.source_id={$src} AND nr.target_type=%s";$params=array($r,get_current_blog_id(),$st,$tt);if('primary'===$selector)$where.=' AND nr.is_primary=1';return array('sql'=>"(SELECT {$expr} FROM {$this->ntable()} nr WHERE {$where} ORDER BY nr.is_primary DESC,nr.sort_order ASC LIMIT 1)",'params'=>$params);}
    private function nhydrate(array $r):array{$r['source_id']=(int)$r['source_id'];$r['target_id']=(int)$r['target_id'];$r['source_blog_id']=(int)$r['source_blog_id'];$r['target_blog_id']=(int)$r['target_blog_id'];$r['sort_order']=(int)$r['sort_order'];$r['order']=$r['sort_order'];$r['is_primary']=(bool)$r['is_primary'];$r['primary']=$r['is_primary'];$r['meta']=$r['meta']?(json_decode($r['meta'],true)?:array()):array();return $r;}
}
