<?php
namespace CGM\Core\Query;
use CGM\Core\Plugin;

/** Compile traversable relationship paths into bounded correlated SQL. */
final class PathQueryCompiler {
    public function __construct(private Plugin $core){}
    public function condition(string $path,string $operator,mixed $value,string $source_type,string $source_expression):array{
        $segments=array_values(array_filter(array_map('trim',explode('.',$path)),fn($v)=>''!==$v));
        if(!$segments)return array('sql'=>'1=0','params'=>array());
        if('relationship'===$segments[0])array_shift($segments);
        return $this->compile_segments($segments,$operator,$value,$source_type,$source_expression);
    }
    private function compile_segments(array $segments,string $operator,mixed $value,string $source_type,string $source_expression):array{
        if(!$segments)return array('sql'=>'1=0','params'=>array());
        $rel=$this->core->relationships()->relationship_for_path((string)$segments[0],$source_type);
        if(!$rel)return $this->field_condition(implode('.',$segments),$operator,$value,$source_type,$source_expression);
        array_shift($segments);$selector='first';if($segments&&in_array($segments[0],array('primary','first','all'),true))$selector=array_shift($segments);
        if(!$segments)return $this->core->relationships()->sql_condition((string)$rel['id'],$operator,$value,$source_expression,$source_type);
        $property=(string)$segments[0];$meta=array_keys((array)($rel['metadata_schema']??array()));
        if(count($segments)===1&&(in_array($property,array('target','target_id','role','primary','is_primary','order','sort_order'),true)||in_array($property,$meta,true)||str_starts_with($property,'meta:')||str_starts_with($property,'meta.'))){return $this->core->relationships()->sql_property_condition((string)$rel['id'],$property,$operator,$value,$source_expression,$source_type);}
        $target=(string)$rel['target_type'];
        $child=$this->compile_segments($segments,$operator,$value,$target,'{{TARGET_ID}}');
        if(!$child['sql'])return array('sql'=>'1=0','params'=>array());
        return $this->core->relationships()->sql_wrap_condition((string)$rel['id'],$selector,$child['sql'],$child['params'],$source_expression,$source_type);
    }
    public function sort(string $path,string $source_type,string $source_expression,bool $numeric=false):?array{
        $segments=array_values(array_filter(array_map('trim',explode('.',$path)),fn($v)=>''!==$v));if('relationship'===($segments[0]??''))array_shift($segments);if(!$segments)return null;$rel=$this->core->relationships()->relationship_for_path((string)$segments[0],$source_type);if(!$rel)return null;array_shift($segments);$selector='first';if($segments&&in_array($segments[0],array('primary','first','all'),true))$selector=array_shift($segments);if(count($segments)!==1)return null;$prop=(string)$segments[0];$meta=array_keys((array)($rel['metadata_schema']??array()));if(in_array($prop,array('target','target_id','role','primary','is_primary','order','sort_order'),true)||in_array($prop,$meta,true)||str_starts_with($prop,'meta:')||str_starts_with($prop,'meta.'))return $this->core->relationships()->sql_sort_expression((string)$rel['id'],$prop,$selector,$source_expression,$source_type);return $this->target_field_sort($rel,$prop,$selector,$source_expression,$numeric,$source_type);
    }
    private function field_condition(string $field_id,string $op,mixed $value,string $content_type,string $source_expr):array{global $wpdb;$field=$this->core->fields()->get($field_id);if(!$field||!$this->applies($field,$content_type))return array('sql'=>'1=0','params'=>array());if(in_array((string)($field['type']??''),array('date','datetime'),true))$value=\CGM\Core\Support\RelativeDate::expand($value);$source=(string)($field['source']??'');$ct=$this->core->content_types()->get($content_type);$kind=(string)($ct['kind']??'post');$provider=(string)($field['provider']??'');if(in_array($kind,array('post','media'),true)){if('wordpress'===$provider||str_starts_with($provider,'wordpress')){$map=array('ID'=>'ID','post_title'=>'post_title','post_name'=>'post_name','post_status'=>'post_status','post_date'=>'post_date','post_modified'=>'post_modified','post_author'=>'post_author');if(isset($map[$source])){$c=$this->scalar('px.`'.$map[$source].'`',$op,$value);return array('sql'=>"EXISTS (SELECT 1 FROM {$wpdb->posts} px WHERE px.ID={$source_expr} AND {$c['sql']})",'params'=>$c['params']);}}return $this->meta_condition($wpdb->postmeta,'post_id',$source_expr,$source,$op,$value);}if('user'===$kind){$map=array('ID','user_login','user_email','display_name','user_registered','user_url');if(in_array($source,$map,true)){$c=$this->scalar('ux.`'.$source.'`',$op,$value);return array('sql'=>"EXISTS (SELECT 1 FROM {$wpdb->users} ux WHERE ux.ID={$source_expr} AND {$c['sql']})",'params'=>$c['params']);}return $this->meta_condition($wpdb->usermeta,'user_id',$source_expr,$source,$op,$value);}if('term'===$kind){if(in_array($source,array('term_id','name','slug'),true)){$c=$this->scalar('tx.`'.$source.'`',$op,$value);return array('sql'=>"EXISTS (SELECT 1 FROM {$wpdb->terms} tx WHERE tx.term_id={$source_expr} AND {$c['sql']})",'params'=>$c['params']);}return $this->meta_condition($wpdb->termmeta,'term_id',$source_expr,$source,$op,$value);}return array('sql'=>'1=0','params'=>array());}
    private function target_field_sort(array $rel,string $field_id,string $selector,string $source_expr,bool $numeric,string $actual_source_type):?array{global $wpdb;$field=$this->core->fields()->get($field_id);$target=(string)$rel['target_type'];if(!$field||!$this->applies($field,$target))return null;$source=(string)($field['source']??'');$store=$this->core->relationships()->store((string)($rel['store']??'core'));if(!($store instanceof \CGM\Core\Relationships\CoreRelationshipStore))return null;$table=$wpdb->prefix.'cgm_core_relationships';$where="cr.relationship_key=%s AND cr.source_type=%s AND cr.source_id={$source_expr} AND cr.target_type=%s";$params=array((string)$rel['id'],('*'===(string)($rel['source_type']??''))?$actual_source_type:(string)$rel['source_type'],$target);if('primary'===$selector)$where.=' AND cr.is_primary=1';$ct=$this->core->content_types()->get($target);$kind=(string)($ct['kind']??'post');if(in_array($kind,array('post','media'),true)&&in_array($source,array('ID','post_title','post_name','post_status','post_date','post_modified','post_author'),true)){$expr="(SELECT px.`{$source}` FROM {$table} cr JOIN {$wpdb->posts} px ON px.ID=cr.target_id WHERE {$where} ORDER BY cr.is_primary DESC,cr.sort_order ASC LIMIT 1)";return array('sql'=>$expr,'params'=>$params);}if(in_array($kind,array('post','media'),true)&&$source){$expr="(SELECT ".($numeric?'CAST(pm.meta_value AS DECIMAL(30,10))':'pm.meta_value')." FROM {$table} cr JOIN {$wpdb->postmeta} pm ON pm.post_id=cr.target_id AND pm.meta_key=%s WHERE {$where} ORDER BY cr.is_primary DESC,cr.sort_order ASC,pm.meta_id DESC LIMIT 1)";return array('sql'=>$expr,'params'=>array_merge(array($source),$params));}return null;}
    private function meta_condition(string $table,string $idcol,string $source_expr,string $key,string $op,mixed $value):array{if(!$key)return array('sql'=>'1=0','params'=>array());if(in_array($op,array('EXISTS','NOT EXISTS'),true))return array('sql'=>('NOT EXISTS'===$op?'NOT ':'')."EXISTS (SELECT 1 FROM {$table} mx WHERE mx.{$idcol}={$source_expr} AND mx.meta_key=%s)",'params'=>array($key));$positive=array('!='=>'=','NOT IN'=>'IN','NOT LIKE'=>'LIKE','NOT BETWEEN'=>'BETWEEN')[$op]??$op;$c=$this->scalar('mx.meta_value',$positive,$value);$sql="EXISTS (SELECT 1 FROM {$table} mx WHERE mx.{$idcol}={$source_expr} AND mx.meta_key=%s AND {$c['sql']})";if(in_array($op,array('!=','NOT IN','NOT LIKE','NOT BETWEEN'),true))$sql='NOT '.$sql;return array('sql'=>$sql,'params'=>array_merge(array($key),$c['params']));}
    private function scalar(string $expr,string $op,mixed $value):array{global $wpdb;$op=strtoupper($op);if(in_array($op,array('IN','NOT IN'),true)){$vals=is_array($value)?$value:array_filter(array_map('trim',explode(',',(string)$value)));if(!$vals)return array('sql'=>'NOT IN'===$op?'1=1':'1=0','params'=>array());return array('sql'=>$expr.' '.$op.' ('.implode(',',array_fill(0,count($vals),'%s')).')','params'=>array_values($vals));}if(in_array($op,array('BETWEEN','NOT BETWEEN'),true)){$vals=is_array($value)?array_values($value):array_map('trim',explode(',',(string)$value));if(count($vals)<2)return array('sql'=>'NOT BETWEEN'===$op?'1=1':'1=0','params'=>array());return array('sql'=>$expr.' '.$op.' %s AND %s','params'=>array($vals[0],$vals[1]));}if(in_array($op,array('LIKE','NOT LIKE'),true))return array('sql'=>$expr.' '.$op.' %s','params'=>array('%'.$wpdb->esc_like((string)$value).'%'));if(!in_array($op,array('=','!=','>','>=','<','<='),true))$op='=';return array('sql'=>$expr.' '.$op.' %s','params'=>array($value));}
    private function applies(array $field,string $type):bool{$types=(array)($field['content_types']??array('*'));return in_array('*',$types,true)||in_array($type,$types,true);}
}
