<?php
namespace CGM\Core\Query;
final class QueryValidator {
    private const OPS=array('=','!=','>','>=','<','<=','LIKE','NOT LIKE','IN','NOT IN','EXISTS','NOT EXISTS','BETWEEN','NOT BETWEEN');
    public function normalize(array $query):array{$query=wp_parse_args($query,array('content_type'=>'post','status'=>array('publish'),'filters'=>array(),'sort'=>array(array('field'=>'post.date','order'=>'DESC')),'limit'=>10,'page'=>1,'offset'=>0,'search'=>'','cache'=>true,'cache_ttl'=>120,'display'=>'list','exposed_filters'=>array(),'aggregate'=>array()));$query['content_type']=sanitize_key((string)$query['content_type']);$query['status']=$this->strings($query['status']?:array('publish'));$query['limit']=max(1,min(100,absint($query['limit'])));$query['page']=max(1,absint($query['page']));$query['offset']=max(0,absint($query['offset']));$query['search']=sanitize_text_field((string)$query['search']);$query['cache']=!empty($query['cache']);$query['cache_ttl']=max(15,min(HOUR_IN_SECONDS,absint($query['cache_ttl'])));$query['display']=sanitize_key((string)($query['display']??'list'));$query['filters']=$this->normalize_group(is_array($query['filters'])?$query['filters']:array());if(isset($query['sort'])&&is_array($query['sort'])&&(isset($query['sort']['field'])||isset($query['sort']['path']))){$query['sort']=array($query['sort']);}$sorts=array();foreach((array)$query['sort'] as $sort){if(!is_array($sort))continue;$field=sanitize_text_field((string)($sort['field']??''));$path=sanitize_text_field((string)($sort['path']??''));if(!$field&&!$path)continue;$sorts[]=array('field'=>$field,'path'=>$path,'order'=>strtoupper((string)($sort['order']??'DESC'))==='ASC'?'ASC':'DESC','numeric'=>!empty($sort['numeric']));}$query['sort']=$sorts;$query['exposed_filters']=$this->exposed_filters($query['exposed_filters']??array());$query['aggregate']=$this->aggregate($query['aggregate']??array());return $query;}
    public function operators():array{return self::OPS;}
    private function exposed_filters(mixed $filters):array{$out=array();foreach((array)$filters as $f){if(is_string($f)){$field=sanitize_text_field($f);if($field)$out[]=array('field'=>$field,'label'=>'','input'=>'text','options'=>array());}elseif(is_array($f)){$field=sanitize_text_field((string)($f['field']??''));if($field)$out[]=array('field'=>$field,'label'=>sanitize_text_field((string)($f['label']??$field)),'input'=>sanitize_key((string)($f['input']??'text')),'options'=>$this->options($f['options']??array()));}}return $out;}
    private function options(mixed $o):array{$out=array();foreach((array)$o as $v=>$l)$out[sanitize_text_field((string)$v)]=sanitize_text_field((string)$l);return $out;}
    private function aggregate(mixed $agg):array{if(!is_array($agg)||empty($agg))return array();return array('group_by'=>sanitize_text_field((string)($agg['group_by']??'')),'function'=>strtoupper((string)($agg['function']??'COUNT')),'field'=>sanitize_text_field((string)($agg['field']??'')),'limit'=>max(1,min(500,absint($agg['limit']??50))));}
    private function normalize_group(array $group):array{$out=array('relation'=>strtoupper((string)($group['relation']??'AND'))==='OR'?'OR':'AND','rules'=>array());$rules=isset($group['rules'])?(array)$group['rules']:$group;foreach($rules as $rule){if(!is_array($rule))continue;if(isset($rule['relation'])||isset($rule['rules'])){$nested=$this->normalize_group($rule);if($nested['rules'])$out['rules'][]=$nested;continue;}$type=sanitize_key((string)($rule['type']??'field'));$op=strtoupper(trim((string)($rule['operator']??'=')));if(!in_array($op,self::OPS,true))$op='=';$out['rules'][]=array('type'=>$type,'field'=>sanitize_text_field((string)($rule['field']??'')),'relationship'=>sanitize_key((string)($rule['relationship']??'')),'property'=>sanitize_text_field((string)($rule['property']??'')),'path'=>sanitize_text_field((string)($rule['path']??'')),'taxonomy'=>sanitize_key((string)($rule['taxonomy']??'')),'reverse'=>!empty($rule['reverse']),'operator'=>$op,'value'=>$this->value($rule['value']??''));}return $out;}
    private function value(mixed $v):mixed{if(is_array($v))return array_map(fn($x)=>is_scalar($x)?sanitize_text_field((string)$x):'',$v);return is_scalar($v)?sanitize_text_field((string)$v):'';}
    private function strings(mixed $v):array{return array_values(array_filter(array_map('sanitize_key',is_array($v)?$v:array($v))));}
}
