<?php
namespace CGM\Core\Query\Providers;

use CGM\Core\Contracts\QueryProviderInterface;
use CGM\Core\Plugin;
use CGM\Core\Query\QueryPlan;
use CGM\Core\Query\QueryResult;

final class TermQueryProvider implements QueryProviderInterface {
    private array $dependencies = array();
    public function __construct( private Plugin $core ) {}
    public function id(): string { return 'wordpress-terms'; }
    public function supports( array $content_type ): bool { return 'term' === ( $content_type['kind'] ?? '' ); }
    public function run( array $query, array $context, array $content_type ): QueryResult {
        global $wpdb; $started=microtime(true);$plan=$this->plan($query,$context,$content_type);$count=$this->prepare($plan->count_sql,$plan->count_params);$total=(int)$wpdb->get_var($count);$sql=$this->prepare($plan->sql,$plan->params);$ids=array_map('absint',(array)$wpdb->get_col($sql));$items=array();if($ids){$terms=get_terms(array('taxonomy'=>(string)$content_type['subtype'],'include'=>$ids,'hide_empty'=>false));if(!is_wp_error($terms)){$map=array();foreach($terms as $t)$map[$t->term_id]=$t;foreach($ids as $id)if(isset($map[$id]))$items[]=$map[$id];}}return new QueryResult($items,$total,(int)$query['page'],(int)$query['limit'],array('provider'=>$this->id(),'plan'=>$plan,'sql'=>current_user_can('manage_cgm_queries')?$sql:'','count_sql'=>current_user_can('manage_cgm_queries')?$count:'','execution_ms'=>round((microtime(true)-$started)*1000,2),'dependencies'=>$plan->dependencies));
    }
    public function explain(array $query,array $context,array $content_type):array{return array('provider'=>$this->id(),'plan'=>$this->plan($query,$context,$content_type));}
    private function plan(array $query,array $context,array $content_type):QueryPlan{global $wpdb;$this->dependencies=array('content:'.(string)$content_type['id']);$taxonomy=(string)($content_type['subtype']??$content_type['taxonomy']??'');$where=array('tt.taxonomy=%s');$params=array($taxonomy);if(''!==(string)($query['search']??'')){$like='%'.$wpdb->esc_like((string)$query['search']).'%';$where[]='(t.name LIKE %s OR t.slug LIKE %s OR tt.description LIKE %s)';array_push($params,$like,$like,$like);} $filter=$this->group((array)($query['filters']??array()),'t.term_id',(string)$content_type['id']);if($filter['sql']){$where[]='('.$filter['sql'].')';$params=array_merge($params,$filter['params']);}$order=$this->sort((array)($query['sort']??array()),(string)$content_type['id']);$limit=max(1,(int)$query['limit']);$offset=(max(1,(int)$query['page'])-1)*$limit+max(0,(int)$query['offset']);$base=" FROM {$wpdb->terms} t JOIN {$wpdb->term_taxonomy} tt ON tt.term_id=t.term_id WHERE ".implode(' AND ',$where);$count='SELECT COUNT(DISTINCT t.term_id)'.$base;$sql='SELECT DISTINCT t.term_id'.$base.' ORDER BY '.$order['sql'].' LIMIT %d OFFSET %d';return new QueryPlan($this->id(),(string)$content_type['id'],$sql,array_merge($params,$order['params'],array($limit,$offset)),$count,$params,array(array('type'=>'term-query','taxonomy'=>$taxonomy)),array_values(array_unique($this->dependencies)));}
    private function group(array $group,string $source,string $content_type):array{$rules=(array)($group['rules']??array());if(!$rules)return array('sql'=>'','params'=>array());$parts=array();$params=array();foreach($rules as $r){if(!is_array($r))continue;$c=isset($r['rules'])||isset($r['relation'])?$this->group($r,$source,$content_type):$this->rule($r,$source,$content_type);if($c['sql']){$parts[]='('.$c['sql'].')';$params=array_merge($params,$c['params']);}}return array('sql'=>implode('OR'===strtoupper((string)($group['relation']??'AND'))?' OR ':' AND ',$parts),'params'=>$params);}
    private function rule(array $r,string $source,string $content_type):array{global $wpdb;$type=sanitize_key((string)($r['type']??'field'));$op=strtoupper((string)($r['operator']??'='));$value=$r['value']??'';if('path'===$type){$path=sanitize_text_field((string)($r['path']??''));$this->dependencies[]='path:'.$path;return (new \CGM\Core\Query\PathQueryCompiler($this->core))->condition($path,$op,$value,$content_type,$source);}if('relationship_property'===$type){$rel=sanitize_key((string)($r['relationship']??''));$property=sanitize_text_field((string)($r['property']??''));$this->dependencies[]='relationship:'.$rel;return $this->core->relationships()->sql_property_condition($rel,$property,$op,$value,$source,$content_type);} if('relationship'===$type){$rel=sanitize_key((string)($r['relationship']??''));$this->dependencies[]='relationship:'.$rel;return $this->core->relationships()->sql_condition($rel,$op,$value,$source,$content_type);}if('relationship_reverse'===$type){$rel=sanitize_key((string)($r['relationship']??''));$this->dependencies[]='relationship:'.$rel;return $this->core->relationships()->sql_reverse_condition($rel,$op,$value,$source);}if('relationship_count'===$type){$rel=sanitize_key((string)($r['relationship']??''));$this->dependencies[]='relationship:'.$rel;return $this->core->relationships()->sql_count_condition($rel,$op,$value,$source,!empty($r['reverse']));}if('taxonomy'===$type)return array('sql'=>'1=0','params'=>array());$id=(string)($r['field']??'');$f=$this->core->fields()->get($id);if(!$f||!$this->field_applies($f,$content_type))return array('sql'=>'1=0','params'=>array());$this->dependencies[]='field:'.$id;$src=(string)($f['source']??'');if('wordpress-term'===($f['provider']??'')&&in_array($src,array('term_id','name','slug','description','parent','count'),true)){$expr=in_array($src,array('description','parent','count'),true)?'tt.`'.$src.'`':'t.`'.$src.'`';return $this->scalar($expr,$op,$value);}if(!$src)return array('sql'=>'1=0','params'=>array());if(in_array($op,array('EXISTS','NOT EXISTS'),true))return array('sql'=>('NOT EXISTS'===$op?'NOT ':'')."EXISTS (SELECT 1 FROM {$wpdb->termmeta} tm WHERE tm.term_id=t.term_id AND tm.meta_key=%s)",'params'=>array($src));$positive=array('!='=>'=','NOT IN'=>'IN','NOT LIKE'=>'LIKE')[$op]??$op;$cond=$this->scalar('tm.meta_value',$positive,$value);$sql="EXISTS (SELECT 1 FROM {$wpdb->termmeta} tm WHERE tm.term_id=t.term_id AND tm.meta_key=%s AND {$cond['sql']})";if(in_array($op,array('!=','NOT IN','NOT LIKE'),true))$sql='NOT '.$sql;return array('sql'=>$sql,'params'=>array_merge(array($src),$cond['params']));}
    private function scalar(string $expr,string $op,mixed $value):array{global $wpdb;if(in_array($op,array('IN','NOT IN'),true)){$vals=is_array($value)?$value:array_filter(array_map('trim',explode(',',(string)$value)));if(!$vals)return array('sql'=>'NOT IN'===$op?'1=1':'1=0','params'=>array());return array('sql'=>$expr.' '.$op.' ('.implode(',',array_fill(0,count($vals),'%s')).')','params'=>array_values($vals));}if(in_array($op,array('LIKE','NOT LIKE'),true))return array('sql'=>$expr.' '.$op.' %s','params'=>array('%'.$wpdb->esc_like((string)$value).'%'));if(!in_array($op,array('=','!=','>','>=','<','<='),true))$op='=';return array('sql'=>$expr.' '.$op.' %s','params'=>array($value));}
    private function sort(array $sorts,string $content_type):array{global $wpdb;$parts=array();$params=array();foreach($sorts as $s){$path=sanitize_text_field((string)($s['path']??''));$order='ASC'===strtoupper((string)($s['order']??'DESC'))?'ASC':'DESC';if($path){$compiled=(new \CGM\Core\Query\PathQueryCompiler($this->core))->sort($path,$content_type,'t.term_id',!empty($s['numeric']));if($compiled){$parts[]=$compiled['sql'].' '.$order;$params=array_merge($params,$compiled['params']);}continue;}$f=$this->core->fields()->get((string)($s['field']??''));if(!$f||empty($f['sortable'])||!$this->field_applies($f,$content_type))continue;$order='ASC'===strtoupper((string)($s['order']??'DESC'))?'ASC':'DESC';$src=(string)($f['source']??'');if('wordpress-term'===($f['provider']??'')&&in_array($src,array('term_id','name','slug','description','parent','count'),true)){$parts[]=(in_array($src,array('description','parent','count'),true)?'tt.`'.$src.'`':'t.`'.$src.'`').' '.$order;}elseif($src){$parts[]="(SELECT tm_sort.meta_value FROM {$wpdb->termmeta} tm_sort WHERE tm_sort.term_id=t.term_id AND tm_sort.meta_key=%s ORDER BY tm_sort.meta_id DESC LIMIT 1) {$order}";$params[]=$src;}}if(!$parts)$parts[]='t.name ASC';$parts[]='t.term_id ASC';return array('sql'=>implode(', ',$parts),'params'=>$params);}
    private function field_applies(array $field,string $content_type):bool{$types=(array)($field['content_types']??array('*'));return in_array('*',$types,true)||in_array($content_type,$types,true);}
    private function prepare(string $sql,array $params):string{global $wpdb;return $params?$wpdb->prepare($sql,...$params):$sql;}
}
