<?php
namespace CGM\Core\Providers\ACF;
use CGM\Core\Contracts\ProviderInterface;use CGM\Core\Plugin;use CGM\Core\Objects\ObjectReference;
final class ACFProvider implements ProviderInterface {
    public function id():string{return 'acf';}
    public function register(Plugin $core):void{if(!function_exists('acf_get_field_groups'))return;$core->providers()->register(array('id'=>'acf','label'=>'Advanced Custom Fields','version'=>defined('ACF_VERSION')?ACF_VERSION:'','capabilities'=>array('fields','dynamic_data'),'status'=>'ready'));foreach(acf_get_field_groups() as $group){$locations=$this->locations($group,$core);foreach(acf_get_fields($group)?:array() as $field)$this->field($core,$field,$locations,(string)($group['title']??''));}}
    private function field(Plugin $core,array $field,array $content_types,string $group):void{$name=(string)($field['name']??'');if(!$name)return;$acf_type=(string)($field['type']??'text');if(in_array($acf_type,array('tab','message','accordion'),true))return;$type=$this->type($acf_type);$id='acf.'.$name;$core->fields()->register(array('id'=>$id,'label'=>(string)($field['label']??$name),'provider'=>'acf','provider_group'=>$group,'source'=>$name,'type'=>$type,'acf_type'=>$acf_type,'queryable'=>!in_array($acf_type,array('gallery','repeater','flexible_content','group'),true),'sortable'=>in_array($acf_type,array('number','range','date_picker','date_time_picker','text','select','true_false'),true),'content_types'=>$content_types?:array('*'),'operators'=>$this->operators($type,$acf_type),'dynamic'=>true,'public'=>(bool)apply_filters('cgm_core/acf_field_public',false,$field,$content_types)));$core->dynamic_data()->register(array('id'=>$id,'label'=>(string)($field['label']??$name),'type'=>$type,'group'=>'ACF','provider'=>'acf','public'=>(bool)apply_filters('cgm_core/acf_field_public',false,$field,$content_types),'resolve'=>static fn($o)=>function_exists('get_field')?get_field($name,self::object_id($o)):null));foreach((array)($field['sub_fields']??array()) as $sub)$this->field($core,$sub,$content_types,$group);}
    private function type(string $t):string{if(in_array($t,array('number','range'),true))return 'number';if('true_false'===$t)return 'boolean';if(in_array($t,array('image','file'),true))return 'media';if(in_array($t,array('relationship','post_object','user','taxonomy'),true))return 'relationship';if(in_array($t,array('date_picker','date_time_picker','time_picker'),true))return 'datetime';return 'string';}
    private function operators(string $type,string $acf):array{if('number'===$type||'datetime'===$type)return array('=','!=','>','>=','<','<=','BETWEEN','NOT BETWEEN','EXISTS','NOT EXISTS');if('relationship'===$type)return array('=','!=','LIKE','NOT LIKE','EXISTS','NOT EXISTS');return array('=','!=','LIKE','NOT LIKE','IN','NOT IN','EXISTS','NOT EXISTS');}
    private function locations(array $group,Plugin $core):array{$out=array();foreach((array)($group['location']??array()) as $or){foreach((array)$or as $rule){if(($rule['operator']??'')!=='==')continue;$param=(string)($rule['param']??'');$value=sanitize_key((string)($rule['value']??''));if('post_type'===$param&&$core->content_types()->has($value))$out[]=$value;elseif('attachment'===$param)$out[]='media';elseif('taxonomy'===$param&&$core->content_types()->has('term_'.$value))$out[]='term_'.$value;elseif(in_array($param,array('user_form','user_role'),true))$out[]='user';}}return array_values(array_unique($out));}
    private static function object_id(mixed $o):mixed{if($o instanceof ObjectReference){if('user'===$o->content_type)return 'user_'.$o->id;if(str_starts_with($o->content_type,'term_'))return 'term_'.$o->id;return $o->id;}return $o instanceof \WP_Post?$o->ID:($o instanceof \WP_User?'user_'.$o->ID:($o instanceof \WP_Term?'term_'.$o->term_id:($o?:get_the_ID())));}
}
