<?php
namespace CGM\Core\Providers\WordPress;

use CGM\Core\Contracts\ProviderInterface;
use CGM\Core\Plugin;
use CGM\Core\Objects\Adapters\{PostObjectAdapter,MediaObjectAdapter,UserObjectAdapter,TermObjectAdapter};
use CGM\Core\Objects\ObjectReference;
use CGM\Core\Query\Providers\{PostQueryProvider,UserQueryProvider,TermQueryProvider};

final class WordPressProvider implements ProviderInterface {
    public function id(): string { return 'wordpress'; }
    public function register( Plugin $core ): void {
        $core->providers()->register( array('id'=>'wordpress','label'=>'WordPress','version'=>get_bloginfo('version'),'capabilities'=>array('content','fields','dynamic_data','taxonomies','users','media','query.posts','query.users','query.terms'),'status'=>'ready') );
        foreach ( get_post_types( array(), 'objects' ) as $pt ) {
            if ( 'attachment' === $pt->name ) { continue; }
            if ( empty( $pt->public ) && empty( $pt->show_ui ) ) { continue; }
            $core->content_types()->register( array('id'=>$pt->name,'label'=>$pt->labels->singular_name,'plural_label'=>$pt->labels->name,'kind'=>'post','subtype'=>$pt->name,'provider'=>'wordpress','query_provider'=>'wordpress-posts','public'=>(bool)$pt->public,'rest'=>(bool)$pt->show_in_rest,'supports'=>get_all_post_type_supports($pt->name)) );
        }
        $core->content_types()->register( array('id'=>'media','label'=>__('Media','cgm-core'),'plural_label'=>__('Media','cgm-core'),'kind'=>'media','subtype'=>'attachment','provider'=>'wordpress','query_provider'=>'wordpress-posts','public'=>true,'rest'=>true) );
        $core->content_types()->register( array('id'=>'user','label'=>__('User','cgm-core'),'plural_label'=>__('Users','cgm-core'),'kind'=>'user','subtype'=>'user','provider'=>'wordpress','query_provider'=>'wordpress-users','public'=>false,'rest'=>true) );
        $term_types = array();
        foreach ( get_taxonomies( array( 'show_ui'=>true ), 'objects' ) as $tax ) { $id='term_'.$tax->name;$term_types[]=$id;$core->content_types()->register(array('id'=>$id,'label'=>$tax->labels->singular_name,'plural_label'=>$tax->labels->name,'kind'=>'term','subtype'=>$tax->name,'taxonomy'=>$tax->name,'provider'=>'wordpress','query_provider'=>'wordpress-terms','public'=>(bool)$tax->public,'rest'=>(bool)$tax->show_in_rest)); }
        $core->objects()->register_adapter( new PostObjectAdapter() ); $core->objects()->register_adapter( new MediaObjectAdapter() ); $core->objects()->register_adapter( new UserObjectAdapter() ); $core->objects()->register_adapter( new TermObjectAdapter() );
        $core->query_providers()->register( new PostQueryProvider( $core ) ); $core->query_providers()->register( new UserQueryProvider( $core ) ); $core->query_providers()->register( new TermQueryProvider( $core ) );
        $this->post_fields($core); $this->user_fields($core); $this->term_fields($core,$term_types); $this->registered_meta($core,$term_types); $this->dynamic_data($core); $this->register_facets($core);
    }
    private function register_facets(Plugin $core):void{foreach(array('category','post_tag') as $tax){if(!taxonomy_exists($tax))continue;$t=get_taxonomy($tax);$core->facets()->register(array('id'=>'taxonomy.'.$tax,'label'=>$t->labels->name,'taxonomy'=>$tax,'content_types'=>array('post')));}}
    private function post_fields(Plugin $core):void{$fields=array('post.title'=>array('Title','post_title','string',array('=','!=','LIKE','NOT LIKE')),'post.slug'=>array('Slug','post_name','string',array('=','!=','LIKE')),'post.author'=>array('Author','post_author','integer',array('=','!=','IN','NOT IN')),'post.status'=>array('Status','post_status','string',array('=','!=','IN','NOT IN')),'post.date'=>array('Publish date','post_date','datetime',array('=','!=','>','>=','<','<=','BETWEEN','NOT BETWEEN')),'post.modified'=>array('Modified date','post_modified','datetime',array('=','!=','>','>=','<','<=','BETWEEN','NOT BETWEEN')),'post.id'=>array('Post ID','ID','integer',array('=','!=','>','>=','<','<=','IN','NOT IN')),'post.parent'=>array('Parent ID','post_parent','integer',array('=','!=','IN','NOT IN')),'post.order'=>array('Menu order','menu_order','integer',array('=','!=','>','>=','<','<=')),'media.mime'=>array('MIME type','post_mime_type','string',array('=','!=','LIKE','IN','NOT IN')));$post_types=array();foreach($core->content_types()->all() as $ct){if(in_array((string)($ct['kind']??''),array('post','media'),true))$post_types[]=(string)$ct['id'];}foreach($fields as $id=>$f){$types='media.mime'===$id?array('media'):$post_types;$core->fields()->register(array('id'=>$id,'label'=>__($f[0],'cgm-core'),'source'=>$f[1],'type'=>$f[2],'operators'=>$f[3],'provider'=>'wordpress','queryable'=>true,'sortable'=>true,'content_types'=>$types,'dynamic'=>true,'public'=>true));}}
    private function user_fields(Plugin $core):void{$fields=array('user.id'=>array('User ID','ID','integer'),'user.login'=>array('Login','user_login','string'),'user.email'=>array('Email','user_email','string'),'user.name'=>array('Display name','display_name','string'),'user.registered'=>array('Registered','user_registered','datetime'),'user.url'=>array('Website','user_url','url'),'user.role'=>array('Role','role','string'));foreach($fields as $id=>$f)$core->fields()->register(array('id'=>$id,'label'=>__($f[0],'cgm-core'),'source'=>$f[1],'type'=>$f[2],'operators'=>$this->operators($f[2]),'provider'=>'wordpress-user','queryable'=>true,'sortable'=>'role'!==$f[1],'content_types'=>array('user'),'dynamic'=>true,'public'=>'user.email'!==$id));}
    private function term_fields(Plugin $core,array $term_types):void{$fields=array('term.id'=>array('Term ID','term_id','integer'),'term.name'=>array('Name','name','string'),'term.slug'=>array('Slug','slug','string'),'term.description'=>array('Description','description','string'),'term.parent'=>array('Parent','parent','integer'),'term.count'=>array('Count','count','integer'));foreach($fields as $id=>$f)$core->fields()->register(array('id'=>$id,'label'=>__($f[0],'cgm-core'),'source'=>$f[1],'type'=>$f[2],'operators'=>$this->operators($f[2]),'provider'=>'wordpress-term','queryable'=>true,'sortable'=>true,'content_types'=>$term_types,'dynamic'=>true,'public'=>true));}
    private function registered_meta(Plugin $core,array $term_types):void{if(!function_exists('get_registered_meta_keys'))return;foreach(get_post_types(array('show_ui'=>true),'names') as $pt){$ct='attachment'===$pt?'media':$pt;foreach((array)get_registered_meta_keys('post',$pt) as $key=>$args)$this->register_meta($core,'post',$ct,$key,$args);}foreach((array)get_registered_meta_keys('user','') as $key=>$args)$this->register_meta($core,'user','user',$key,$args);foreach($term_types as $ct){$tax=substr($ct,5);foreach((array)get_registered_meta_keys('term',$tax) as $key=>$args)$this->register_meta($core,'term',$ct,$key,$args);}}
    private function register_meta(Plugin $core,string $kind,string $ct,string $key,array $args):void{if(str_starts_with((string)$key,'_')&&!($args['show_in_rest']??false))return;$type=(string)($args['type']??'string');$id='meta.'.$kind.'.'.$key;$core->fields()->register(array('id'=>$id,'label'=>ucwords(str_replace(array('_','-'),' ',(string)$key)),'provider'=>'wordpress-meta','source'=>$key,'type'=>$type,'queryable'=>true,'sortable'=>in_array($type,array('integer','number','string','datetime'),true),'content_types'=>array($ct),'operators'=>$this->operators($type),'dynamic'=>true,'rest'=>!empty($args['show_in_rest']),'public'=>!str_starts_with($key,'_')));$core->dynamic_data()->register(array('id'=>$id,'label'=>ucwords(str_replace('_',' ',$key)),'type'=>$type,'group'=>'WordPress Meta','provider'=>'wordpress','public'=>!str_starts_with($key,'_'),'resolve'=>static function($o)use($kind,$key){$id=$o instanceof ObjectReference?$o->id:($o instanceof \WP_Post||$o instanceof \WP_User?$o->ID:($o instanceof \WP_Term?$o->term_id:absint($o)));return match($kind){'user'=>get_user_meta($id,$key,true),'term'=>get_term_meta($id,$key,true),default=>get_post_meta($id,$key,true)};}));}
    private function dynamic_data(Plugin $core):void{$defs=array(array('post.title','Post title','string',static fn($o)=>get_the_title(self::object_id($o))),array('post.url','Post URL','url',static fn($o)=>get_permalink(self::object_id($o))),array('post.id','Post ID','integer',static fn($o)=>self::object_id($o)),array('post.excerpt','Post excerpt','string',static fn($o)=>get_the_excerpt(self::object_id($o))),array('post.featured_image_id','Featured image ID','media',static fn($o)=>get_post_thumbnail_id(self::object_id($o))),array('post.author.name','Author name','string',static function($o){$id=self::object_id($o);return get_the_author_meta('display_name',(int)get_post_field('post_author',$id));}),array('post.author.id','Author ID','integer',static fn($o)=>(int)get_post_field('post_author',self::object_id($o))));foreach($defs as $d)$core->dynamic_data()->register(array('id'=>$d[0],'label'=>__($d[1],'cgm-core'),'type'=>$d[2],'group'=>'WordPress','provider'=>'wordpress','resolve'=>$d[3]));}
    private function operators(string $type):array{return in_array($type,array('integer','number','datetime'),true)?array('=','!=','>','>=','<','<=','IN','NOT IN','BETWEEN','NOT BETWEEN','EXISTS','NOT EXISTS'):array('=','!=','LIKE','NOT LIKE','IN','NOT IN','EXISTS','NOT EXISTS');}
    private static function object_id(mixed $o):int{return $o instanceof ObjectReference?$o->id:($o instanceof \WP_Post||$o instanceof \WP_User?(int)$o->ID:($o instanceof \WP_Term?(int)$o->term_id:absint($o?:get_the_ID())));}
}
