<?php
namespace CGM\Core\REST;use CGM\Core\Plugin;
final class EditorController extends BaseController {
    public function __construct(private Plugin $core){}
    public function register_routes():void{register_rest_route($this->namespace,'/editor/(?P<post_id>\d+)/controls',array('methods'=>\WP_REST_Server::READABLE,'callback'=>array($this,'controls'),'permission_callback'=>array($this,'can_edit_post'),'args'=>array('post_id'=>array('type'=>'integer','required'=>true,'minimum'=>1,'sanitize_callback'=>'absint'))));register_rest_route($this->namespace,'/editor/(?P<post_id>\d+)/control/(?P<control>[a-z0-9_-]+)',array(array('methods'=>\WP_REST_Server::CREATABLE,'callback'=>array($this,'save'),'permission_callback'=>array($this,'can_edit_post'),'args'=>array('post_id'=>array('type'=>'integer','required'=>true,'minimum'=>1,'sanitize_callback'=>'absint'),'control'=>array('required'=>true,'type'=>'string','sanitize_callback'=>'sanitize_key'),'items'=>array('required'=>true,'type'=>'array','maxItems'=>500))),array('methods'=>\WP_REST_Server::READABLE,'callback'=>array($this,'search'),'permission_callback'=>array($this,'can_edit_post'),'args'=>array('post_id'=>array('type'=>'integer','required'=>true,'minimum'=>1,'sanitize_callback'=>'absint'),'control'=>array('required'=>true,'type'=>'string','sanitize_callback'=>'sanitize_key'),'search'=>array('type'=>'string','sanitize_callback'=>'sanitize_text_field','default'=>'')))));}
    public function can_edit_post(\WP_REST_Request $r):bool{return current_user_can('edit_post',absint($r['post_id']));}
    public function controls(\WP_REST_Request $r):\WP_REST_Response{$post=get_post(absint($r['post_id']));if(!$post)return rest_ensure_response(array());$out=array();foreach($this->core->editor_controls()->for_post_type($post->post_type) as $c){$get=$c['get']??null;$c['items']=is_callable($get)?array_values(array_filter((array)call_user_func($get,$post->ID,$c))):array();if(!empty($c['relationship']))$c['schema']=$this->core->relationships()->get_type((string)$c['relationship'])??($c['schema']??array());unset($c['get'],$c['set'],$c['search']);$out[]=$c;}return rest_ensure_response($out);}
    public function save(\WP_REST_Request $r):\WP_REST_Response{$c=$this->core->editor_controls()->get((string)$r['control']);if(!$c||!is_callable($c['set']??null))return new \WP_REST_Response(array('message'=>'Unknown control.'),404);$items=array();foreach((array)$r->get_param('items') as $index=>$item){if(is_array($item)){$id=absint($item['id']??0);if(!$id)continue;$clean=array('id'=>$id,'primary'=>!empty($item['primary']),'role'=>sanitize_key((string)($item['role']??'')),'order'=>intval($item['order']??$index),'meta'=>is_array($item['meta']??null)?$item['meta']:array());$items[]=$clean;}else{$id=absint($item);if($id)$items[]=array('id'=>$id,'order'=>$index);}}$ok=(bool)call_user_func($c['set'],absint($r['post_id']),$items,$c);return rest_ensure_response(array('success'=>$ok,'items'=>$ok&&is_callable($c['get']??null)?array_values((array)call_user_func($c['get'],absint($r['post_id']),$c)):$items));}
    public function search(\WP_REST_Request $r):\WP_REST_Response{$c=$this->core->editor_controls()->get((string)$r['control']);if(!$c||!is_callable($c['search']??null))return rest_ensure_response(array());return rest_ensure_response(array_values((array)call_user_func($c['search'],(string)$r->get_param('search'),absint($r['post_id']),$c)));}
}
