<?php
namespace CGM\Core\REST;
use CGM\Core\Plugin;
final class PathController extends BaseController {
    public function __construct(private Plugin $core){}
    public function register():void{
        register_rest_route('cgm-core/v1','/paths',array('methods'=>'GET','callback'=>array($this,'paths'),'permission_callback'=>fn()=>current_user_can('edit_posts'),'args'=>array('content_type'=>array('type'=>'string','required'=>true,'sanitize_callback'=>'sanitize_key'),'prefix'=>array('type'=>'string','sanitize_callback'=>'sanitize_text_field'))));
        register_rest_route('cgm-core/v1','/builder-manifest',array('methods'=>'GET','callback'=>array($this,'manifest'),'permission_callback'=>fn()=>current_user_can('edit_posts')));
    }
    public function paths(\WP_REST_Request $r):\WP_REST_Response{$type=sanitize_key((string)$r['content_type']);$prefix=sanitize_text_field((string)($r['prefix']??''));$current=$type;if($prefix){$segments=array_values(array_filter(explode('.',$prefix)));if('relationship'===($segments[0]??''))array_shift($segments);while($segments){$rel=$this->core->relationships()->relationship_for_path((string)$segments[0],$current);if(!$rel)break;array_shift($segments);if($segments&&in_array($segments[0],array('primary','first','all'),true))array_shift($segments);$current=(string)$rel['target_type'];if($segments)break;}}$items=array();foreach($this->core->fields()->all() as $f){$types=(array)($f['content_types']??array('*'));if(!in_array('*',$types,true)&&!in_array($current,$types,true))continue;$items[]=array('kind'=>'field','id'=>$f['id'],'label'=>$f['label']??$f['id'],'type'=>$f['type']??'string','path'=>trim($prefix.'.'.$f['id'],'.'),'terminal'=>true,'operators'=>$f['operators']??array('=','!='));}foreach($this->core->relationships()->all() as $rel){$types=(array)($rel['source_types']??array($rel['source_type']));if('*'!==($rel['source_type']??'')&&!in_array($current,$types,true))continue;$base=trim($prefix.'.'.$rel['id'],'.');$items[]=array('kind'=>'relationship','id'=>$rel['id'],'label'=>$rel['label']??$rel['id'],'path'=>$base.'.primary','terminal'=>false,'target_type'=>$rel['target_type'],'properties'=>$this->properties($rel));}return rest_ensure_response(array('content_type'=>$type,'resolved_type'=>$current,'prefix'=>$prefix,'items'=>$items));}
    private function properties(array $r):array{$p=array(array('id'=>'target_id','label'=>'Target ID','type'=>'integer'),array('id'=>'role','label'=>'Role','type'=>'string'),array('id'=>'primary','label'=>'Primary','type'=>'boolean'),array('id'=>'order','label'=>'Order','type'=>'integer'));foreach((array)($r['metadata_schema']??array()) as $id=>$d)$p[]=array('id'=>$id,'label'=>$d['label']??$id,'type'=>$d['type']??'string','options'=>$d['options']??array());return $p;}
    public function manifest():\WP_REST_Response{return rest_ensure_response(array('version'=>CGM_CORE_API_VERSION,'query_api'=>CGM_CORE_QUERY_API_VERSION,'dynamic_api'=>CGM_CORE_DYNAMIC_DATA_API_VERSION,'content_types'=>array_values($this->core->content_types()->all()),'fields'=>array_values($this->core->fields()->all()),'relationships'=>array_values($this->core->relationships()->all()),'dynamic_data'=>array_values($this->core->dynamic_data()->all()),'saved_queries'=>$this->core->saved_queries()->list(),'contexts'=>$this->core->context()->tokens(),'builders'=>array_values($this->core->builders()->all())));}
}
